version: "3.8"
services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    networks:
      app_net:
        aliases:
          - nginx
  dev:
    image: mcr.microsoft.com/devcontainers/base:debian
    command: sleep infinity
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
