services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    depends_on:
      - redis
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"